In [1]:
import numpy as np

In [2]:
L1=[1,3,4]
print(L1)

[1, 3, 4]


In [3]:
np.array([1,3,4]) # one dimensional 

array([1, 3, 4])

In [4]:
m1=[[1,2,3],[4,5,6],[7,8,9]]
print(m1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
np.array(m1) #2 dimensional 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr = np.array([[6,63,4]], np.int64)
print(arr)

[[ 6 63  4]]


In [ ]:
arr[0,2]

4

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,50,13)

array([ 0.        ,  4.16666667,  8.33333333, 12.5       , 16.66666667,
       20.83333333, 25.        , 29.16666667, 33.33333333, 37.5       ,
       41.66666667, 45.83333333, 50.        ])

In [15]:
np.eye(4) #matrix of 4*4 with diagonal elements =1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])