In [1]:
    import numpy as np

In [2]:
np.random.rand(3) # n random number from uniform distribution [0,1]

array([0.49070043, 0.23086415, 0.21954288])

In [3]:
np.random.rand(4,4) # uniform distribution

array([[0.46343487, 0.07440005, 0.40397036, 0.01620093],
       [0.49723784, 0.92123568, 0.47683885, 0.49337252],
       [0.42779363, 0.70711284, 0.78551441, 0.81969147],
       [0.0969073 , 0.03972956, 0.73244467, 0.97623854]])

In [4]:
np.random.randn(3) # normal distribution

array([-0.69382096,  0.14402243, -1.23287681])

In [5]:
np.random.randn(4,4) # normal distribution


array([[-1.82114371,  1.20128422, -0.2381707 , -0.31847907],
       [ 1.81572419, -0.2800755 ,  0.28290388,  2.05095233],
       [ 0.99914623,  1.27339505,  1.61261451, -0.84465647],
       [-0.13496377,  0.42214869, -1.12887758, -2.13603866]])

In [6]:
np.random.randint(1,30) # random number between 1 to 30

7

In [7]:
np.random.randint(1,100,10) # 10 random number between 1 to 100

array([11, 73, 24, 32, 85, 85,  1, 17, 80, 65])

In [11]:
np.random.seed(83)
np.random.randint(1,40)  # everytime u will execute u will have same random number because seed value is same 

19

In [13]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.shape

(25,)

In [12]:
np.random.seed(42)
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10])

In [15]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.shape

(25,)

In [17]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
arr.reshape(1,25).shape

(1, 25)

In [19]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [20]:
ranarr

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10])

In [21]:
ranarr.max() # return max value 


42

In [22]:
ranarr.argmax() # return index of max value

3

In [23]:
ranarr.min()  # return min value 

7

In [24]:
ranarr.argmin()  # return index of min value

4

In [25]:
arr.dtype

dtype('int64')

In [26]:
ranarr.dtype

dtype('int64')

In [27]:
import sys 
py_arr= [3,1,5]
py_arr

[3, 1, 5]

In [28]:
sys.getsizeof(1) * len(py_arr)  # size of py_arr

84

In [29]:
np_arr= np.array(py_arr)
np_arr

array([3, 1, 5])

In [30]:
np_arr.itemsize * np_arr.size

24

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(5,5).sum(axis=0)  # axis=0 column wise 

array([50, 55, 60, 65, 70])

In [33]:
arr.reshape(5,5).sum(axis=1)  # axis=1 row wise 

array([ 10,  35,  60,  85, 110])

In [34]:
arr1= np.arange(25,50)
arr1


array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
arr + arr1 # perform - , *, /

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73])

In [36]:
# transpose
arr.reshape(5,5).T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [37]:
np.where(arr>5)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24]),)